package com.mysitehouse.dal.dataobject;

public class MshUserInfoDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msh_user_info.id
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msh_user_info.user_id
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msh_user_info.user_account
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    private String userAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msh_user_info.nick
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    private String nick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msh_user_info.name
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msh_user_info.gender
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msh_user_info.mobile
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msh_user_info.phone
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msh_user_info.email
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msh_user_info.feature
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    private String feature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column msh_user_info.remark
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msh_user_info.id
     *
     * @return the value of msh_user_info.id
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msh_user_info.id
     *
     * @param id the value for msh_user_info.id
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msh_user_info.user_id
     *
     * @return the value of msh_user_info.user_id
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msh_user_info.user_id
     *
     * @param userId the value for msh_user_info.user_id
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msh_user_info.user_account
     *
     * @return the value of msh_user_info.user_account
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public String getUserAccount() {
        return userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msh_user_info.user_account
     *
     * @param userAccount the value for msh_user_info.user_account
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msh_user_info.nick
     *
     * @return the value of msh_user_info.nick
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msh_user_info.nick
     *
     * @param nick the value for msh_user_info.nick
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public void setNick(String nick) {
        this.nick = nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msh_user_info.name
     *
     * @return the value of msh_user_info.name
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msh_user_info.name
     *
     * @param name the value for msh_user_info.name
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msh_user_info.gender
     *
     * @return the value of msh_user_info.gender
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msh_user_info.gender
     *
     * @param gender the value for msh_user_info.gender
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msh_user_info.mobile
     *
     * @return the value of msh_user_info.mobile
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msh_user_info.mobile
     *
     * @param mobile the value for msh_user_info.mobile
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msh_user_info.phone
     *
     * @return the value of msh_user_info.phone
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msh_user_info.phone
     *
     * @param phone the value for msh_user_info.phone
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msh_user_info.email
     *
     * @return the value of msh_user_info.email
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msh_user_info.email
     *
     * @param email the value for msh_user_info.email
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msh_user_info.feature
     *
     * @return the value of msh_user_info.feature
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public String getFeature() {
        return feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msh_user_info.feature
     *
     * @param feature the value for msh_user_info.feature
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public void setFeature(String feature) {
        this.feature = feature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column msh_user_info.remark
     *
     * @return the value of msh_user_info.remark
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column msh_user_info.remark
     *
     * @param remark the value for msh_user_info.remark
     *
     * @mbggenerated Sun Mar 27 22:10:32 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}